project_id = "ytqkunjxhtjsbpdrwsjf"

[auth]
enabled = true
site_url = "https://15f46a1e-4701-482b-98fb-246120c30114.lovableproject.com"

[functions.social-verify]
verify_jwt = false

[functions.ai-moderation]
verify_jwt = true

[functions.voice-transcription]
verify_jwt = true

[functions.ai-market-rate-analysis]
verify_jwt = false

[functions.social-media-scraper]
verify_jwt = false

[functions.press-coverage-analyzer]
verify_jwt = false

[functions.performance-tracker]
verify_jwt = false