// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytqkunjxhtjsbpdrwsjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cWt1bmp4aHRqc2JwZHJ3c2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODMwMzcsImV4cCI6MjA3MzU1OTAzN30.4cxQkkwnniFt5H4ToiNcpi6CxpXCpu4iiSTRUjDoBbw";

// HMR-safe Supabase singleton to prevent multiple GoTrueClient instances
declare global {
  // eslint-disable-next-line no-var
  var __SUPABASE__: SupabaseClient<Database> | undefined;
}

function getSupabaseClient(): SupabaseClient<Database> {
  if (globalThis.__SUPABASE__) return globalThis.__SUPABASE__!;
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      // Use a unique storage key to avoid collisions across clients
      storageKey: 'skipamerica-auth',
    },
  });
  globalThis.__SUPABASE__ = client;
  
  try {
    // stash anon key for auth header helper
    // @ts-ignore
    window.__supabaseAnonKey = SUPABASE_PUBLISHABLE_KEY;
  } catch {}
  
  return client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = getSupabaseClient();